version: "3"

services:
  # setting up MariaDB
  db:
    image: mariadb:10.5
    # important to use on database connection
    # file the same name that the container_name
    # bellow as host
    container_name: "mariadb-server"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db_name
    ports:
      - 8011:3306
    volumes:
      - ./.docker/db:/var/lib/mysql

  # build PHP-FPM apart from Nginx server
  # to change PHP Version update the .docker/php/Dockerfile
  php:
    build: .docker/php
    container_name: "php-server"
    image: server-php-nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"

  #build Nginx default server
  nginx:
    image: nginx
    container_name: "nginx-server"
    volumes:
      # enable SSL
      - .docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - .docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      # Ngixn configs
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # logs
      - .docker/nginx/client-access.log:/var/log/nginx/client-access.log;
      - .docker/nginx/client-error.log:/var/log/nginx/client-error.log;
      # Server root
      - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
      #- "8010:80"
    links:
      - db
      - php
    depends_on:
      - db
      - php
    tty: true

  app:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
